baseURL = "https://keithieopia.com"
languageCode = "en-us"
theme = "koi"

[params]
  title = "Keithieopia"
  author = "Timothy Keith"
  email = "timothykeith@gmail.com"
  description = "Names are unimportant. One person can't change the world. But one plus one plus one starts to add up. This site is my small addition to that equation."
  intro = '''
Hi. Names are unimportant — one person can't change the world.
But one, plus one, plus one… starts to add up. This site is my
small addition to that equation.
'''

  social = [
    ["GitHub", "github", "https://github.com/keithieopia/"],
    ["GitLab", "gitlab", "https://gitlab.com/keithieopia/"],
    ["Keybase", "keybase", "https://keybase.io/timothykeith"],
    ["goodreads", "goodreads", "https://www.goodreads.com/user/show/29557128-timothy"],
    ["IMDb", "imdb", "https://www.imdb.com/user/ur73901400/ratings?sort=user_rating:desc"],
    ["Steam", "steam", "https://steamcommunity.com/id/keithieopia"],
    ["Stack Overflow", "stack-overflow", "https://stackoverflow.com/users/7416714/keithieopia"]
  ]

  httpURL   = "http://keithieopia.com"
  httpsURL  = "https://keithieopia.com"
  torURL    = "http://keith4g2hdg6dzsvjtra3c5pyclcwpam2o5tvjx2tm44tjj7nkhyakyd.onion/"
  source = "https://github.com/keithieopia/keithieopia.com"
