languageCode = "en-us"
title = "Keithieopia"
baseurl = "http://keithieopia.com/"

theme = "solomons"

pygmentsuseclasses = false
pygmentsstyle      = "autumn"

[params]
  author      = "Timothy Keith"
  email       = "timothykeith@gmail.com"
  source      = "https://github.com/keithieopia/keithieopia.com"

  social = [
	["GitHub", "github", "https://github.com/keithieopia/"],
	["GitLab", "gitlab", "https://gitlab.com/keithieopia/"],
	["Keybase", "keybase", "https://keybase.io/timothykeith"],
	["goodreads", "goodreads", "https://www.goodreads.com/user/show/29557128-timothy"],
	["IMDb", "imdb", "https://www.imdb.com/user/ur73901400/ratings?sort=user_rating:desc"],
	["Steam", "steam", "https://steamcommunity.com/id/keithieopia"],
	["Stack Overflow", "stack-overflow", "https://stackoverflow.com/users/7416714/keithieopia"]
  ]

[[menu.footer]]
  name   = "Email"
  url    = "mailto:timothykeith@gmail.com"
  weight = -100
[[menu.footer]]
  name = "License"
  url  = "/license/"
[[menu.footer]]
  name = "Colophon"
  url  = "/colophon/"


[[menu.main]]
  name = "Blog"
  url = "/"
  weight = -100
[[menu.main]]
  name = "Git"
  url = "http://git.keithieopia.com/explore/repos"
