languageCode = "en-us"
title = "Keithieopia"
baseurl = "http://keithieopia.com/"

theme = "solomons"

pygmentsuseclasses = false
pygmentsstyle      = "autumn"

[params]
  author      = "Timothy Keith"
  email       = "timothykeith@gmail.com"
  source      = "https://github.com/keithieopia/keithieopia.com"

[[menu.footer]]
  name   = "Email"
  url    = "mailto:timothykeith@gmail.com"
  weight = -100
[[menu.footer]]
  name = "License"
  url  = "/license/"
[[menu.footer]]
  name = "Colophon"
  url  = "/colophon/"

[[menu.icons]]
  title = "GitHub"
  name = "github"
  url  = "https://github.com/keithieopia/"
[[menu.icons]]
  title = "GitLab"
  name = "gitlab"
  url  = "https://gitlab.com/keithieopia/"
[[menu.icons]]
  title = "Keybase"
  name = "keybase"
  url  = "https://keybase.io/timothykeith"
[[menu.icons]]
  title = "goodreads"
  name = "goodreads"
  url  = "https://www.goodreads.com/user/show/29557128-timothy"
[[menu.icons]]
  title = "IMDb"
  name = "imdb"
  url  = "https://www.imdb.com/user/ur73901400/ratings?sort=user_rating:desc"
[[menu.icons]]
  title = "Steam"
  name = "steam"
  url  = "https://steamcommunity.com/id/keithieopia"
[[menu.icons]]
  title = "Stack Overflow"
  name = "stack-overflow"
  url  = "https://stackoverflow.com/users/7416714/keithieopia"


 
  
[[menu.main]]
  name = "Blog"
  url = "/"
  weight = -100
[[menu.main]]
  name = "Git"
  url = "http://git.keithieopia.com/explore/repos"
