languageCode = "en-us"
title = "Keithieopia"
baseurl = "http://keithieopia.com/"

theme = "solomons"

pygmentsuseclasses = false
pygmentsstyle      = "autumn"

[params]
  author      = "Timothy Keith"
  email       = "timothykeith@gmail.com"
  source      = "https://github.com/keithieopia/keithieopia.com"
  
[[menu.footer]]
  name = "GitHub"
  url  = "https://github.com/keithieopia/"
[[menu.footer]]
  name = "License"
  url  = "/license/"
[[menu.footer]]
  name = "Colophon"
  url  = "/colophon/"

[[menu.main]]
  name = "Blog"
  url = "/"
  weight = -100
[[menu.main]]
  name = "Git"
  url = "http://git.keithieopia.com/explore/repos"
